collections:
  authors:
    output: true
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      image: /assets/images/brand/dm.png

permalink: '/:year/:month/:title.html'

issues_repo: drearymiddle/drearymiddle.github.io

# Useable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-admin

# SEO Tag settings
title: Dreary Middle
tagline: Genuine discussion about our favourite things
description: Genuine discussion about our favourite things! Films, Television and occasionally games, come for real discussions on some of the hottest topics on the internet
url: http://drearymiddle.com
logo: /assets/images/branding/dm.png
twitter:
  username: drearymiddle
  card: summary
social:
  links:
    - https://twitter.com/drearymiddle
    - https://www.youtube.com/channel/UCombRhqo_ES7uYG8TAEkKXA
# webmaster_verifications:
  # google: 
lang: en-GB