collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Useable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Tag settings
title: Dreary Middle
tagline: Genuine discussion about our favourite things
description: Genuine discussion about our favourite things! Movies, Television and occasionally games, come for real discussions on some of the hottest topics on the internet
url: http://drearymiddle.com
logo: /assets/images/branding/dm.png
social:
  links:
    - https://twitter.com/drearymiddle
    - https://www.youtube.com/channel/UCombRhqo_ES7uYG8TAEkKXA
# webmaster_verifications:
  # google: 
lang: en-GB